Bumped ``mypy`` version to 1.4.0
